name: thrillie
repository: https://github.com/Nikron9/thrillie
sdkPath: .fvm/flutter_sdk

packages:
  - .
  - l1_application
  - l1_domain
  - l0_data
  - l2_presentation

scripts:
  test:
    exec: run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.
  analyze:
    exec: flutter analyze
    description: Run `dart analyze` in all packages.
  pubGet:
    exec: flutter pub get
    description: Install all dependencies
  pubCleanCache:
    exec: flutter pub cache clean
    description: Clean all caches
  pubUpgrade:
    exec: flutter pub upgrade
    description: Upgrade all dependencies
  buildRunner:
    exec: flutter pub run build_runner build
    description: Generate necessary code