name: thrillie
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.0.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^4.0.0
  flutter:
    sdk: flutter
  get_it: ^7.0.0
  l0_domain:
    path: l0_domain/
  l1_application:
    path: l1_application/
  l2_frameworks:
    path: l2_frameworks/
  l3_presentation:
    path: l3_presentation/
    
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  melos: ^3.0.0


flutter:
  uses-material-design: true