name: l0_data
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.11.0
  collection: ^1.17.2
  dartx: ^1.2.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  l1_domain:
    path: ../l1_domain/
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
